name: CICD

on:
  push:
    branches: [cicd-docker-ec2]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t jesusverma/node-app-docker-ec2 .
      - name: Publish image to docker hub
        run: docker push jesusverma/node-app-docker-ec2:latest
        
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: docker pull jesusverma/node-app-docker-ec2:latest
      - name: Delete old container
        run: docker rm -f node-app-docker-ec2-container
      - name: Run docker container
        run: docker run -d -p 5000:5000 --name node-app-docker-ec2-container jesusverma/node-app-docker-ec2
        